PyTorch basics

Basics of PyTorch

In [1]:
import torch

In [6]:
t=torch.Tensor(4)
t.dtype

torch.float32

In [7]:
t1=torch.Tensor([1,2,3,4])
t1

tensor([1., 2., 3., 4.])

In [9]:
t2=torch.Tensor([[1,2],[3,4],[5,6]])
t2

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [10]:
t3 = torch.tensor([
    [[1, 1, 3],
     [3, 1, 5]],
    [[5, 1, 1],
     [7, 8, 9.]]])
t3

tensor([[[1., 1., 3.],
         [3., 1., 5.]],

        [[5., 1., 1.],
         [7., 8., 9.]]])

In [11]:
t3.size()

torch.Size([2, 2, 3])

Type Conversions

In [13]:
import numpy as np

x=np.array([[1,3],[3,4]])
x


array([[1, 3],
       [3, 4]])

In [14]:
y=torch.from_numpy(x)
y.dtype

torch.int64